# reports/report_export.py
import pandas as pd
import json
import os
from io import BytesIO
import tempfile
import customtkinter as ctk
from tkinter import messagebox
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image as RLImage, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.pdfgen.canvas import Canvas
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
from jsonschema import validate, ValidationError
from PIL import Image as PILImage, ImageTk
try:
    from pdf2image import convert_from_path
    HAS_PDF2IMAGE = True
except ImportError:
    HAS_PDF2IMAGE = False
import logging
from typing import List, Dict, Optional
from datetime import datetime
from modules.db_setup import get_logs_dir, get_config_dir

# Configure logging 
logs_dir = get_logs_dir()
os.makedirs(logs_dir, exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(os.path.join(logs_dir, "report_export.log")),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class ReportExporter:
    def __init__(self, report_mgr):
        self.report_mgr = report_mgr
        self.config = self.load_config()

    def load_config(self) -> Dict:
        """Load and validate report configuration from JSON file."""
        config_dir = get_config_dir()
        config_path = os.path.join(config_dir, "report_config.json")
        schema_path = os.path.join(config_dir, "report_config_schema.json")
        default_config = {
            "school": {
                "name": "Bar Union Secondary School",
                "p_o_box": "P.O. Box 8021, Dago",
                "contact": "Phone: +1-555-123-4567 | Email: info@springfieldhigh.edu",
                "motto": "Excellence in Education",
                "website": "www.springfieldhigh.edu",
                "logo_path": "",
                "report_logos": {}
            },
            "pdf_formatting": {
                "header_font": "Helvetica-Bold",
                "header_font_size": 16,
                "subheader_font": "Helvetica",
                "subheader_font_size": 12,
                "table_font": "Helvetica",
                "table_font_size": 10,
                "header_color": "#003087",
                "table_header_color": "#4B5EAA",
                "table_row_color": "#F5F6F5",
                "border_color": "#000000",
                "page_margins": {
                    "top": 50,
                    "bottom": 50,
                    "left": 36,
                    "right": 36
                },
                "footer": {
                    "custom_text": "Generated by Reporting System",
                    "additional_fields": [],
                    "font": "Helvetica",
                    "font_size": 10,
                    "text_color": "#003087",
                    "alignment": "left"
                },
                "report_headers": {
                    "student_summary": {"logo_position": "left", "text_alignment": "left", "logo_width": 1, "logo_height": 1},
                    "class_summary": {"logo_position": "center", "text_alignment": "center", "logo_width": 1, "logo_height": 1},
                    "defaulters": {"logo_position": "right", "text_alignment": "right", "logo_width": 1, "logo_height": 1},
                    "surplus": {"logo_position": "left", "text_alignment": "left", "logo_width": 1, "logo_height": 1},
                    "term_summary": {"logo_position": "center", "text_alignment": "center", "logo_width": 1, "logo_height": 1},
                    "issued_summary": {"logo_position": "left", "text_alignment": "left", "logo_width": 1, "logo_height": 1},
                    "overview": {"logo_position": "center", "text_alignment": "center", "logo_width": 1, "logo_height": 1},
                    "stream_ream": {"logo_position": "center", "text_alignment": "center", "logo_width": 1.5, "logo_height": 1.5}
                }
            },
            "excel_formatting": {
                "header_font": "Arial",
                "header_font_size": 12,
                "header_bold": True,
                "cell_font": "Arial",
                "cell_font_size": 10,
                "header_background_color": "#4B5EAA",
                "header_text_color": "#FFFFFF",
                "border_color": "#000000"
            }
        }

        try:
            with open(config_path, 'r') as f:
                config = json.load(f)
            with open(schema_path, 'r') as f:
                schema = json.load(f)
            validate(instance=config, schema=schema)
            logger.info("Successfully validated report_config.json")
            return config
        except FileNotFoundError as e:
            logger.error(f"Configuration file not found: {e}. Using default configuration.")
            return default_config
        except json.JSONDecodeError as e:
            logger.error(f"Error parsing report_config.json: {e}. Using default configuration.")
            return default_config
        except ValidationError as e:
            logger.error(f"Invalid report_config.json: {e.message}. Using default configuration.")
            return default_config

    def build_cover_page(self, report_type: str, styles: Dict) -> List:
        """Build a cover page with larger logo and school details."""
        elements = []
        header_config = self.config["pdf_formatting"]["report_headers"].get(report_type, {"logo_position": "center", "text_alignment": "center", "logo_width": 2, "logo_height": 2})
        logo_path = self.config["school"]["report_logos"].get(report_type, self.config["school"]["logo_path"])
        if os.path.exists(logo_path):
            logo = RLImage(logo_path, width=header_config["logo_width"]*inch, height=header_config["logo_height"]*inch)
            logo.hAlign = header_config["logo_position"].upper()
            elements.append(logo)
        else:
            logger.warning(f"Logo file not found at {logo_path}")
            elements.append(Paragraph("Logo Not Available", styles['Subheader']))
        elements.append(Spacer(1, 0.3*inch))
        elements.append(Paragraph(self.config["school"]["name"], styles['Header']))
        elements.append(Paragraph(self.config["school"]["p_o_box"], styles['Subheader']))
        elements.append(Paragraph(self.config["school"]["contact"], styles['Subheader']))
        elements.append(Paragraph(self.config["school"]["motto"], styles['Subheader']))
        elements.append(Paragraph(self.config["school"]["website"], styles['Subheader']))
        elements.append(Spacer(1, 0.2*inch))
        elements.append(Paragraph(f"{report_type.replace('_', ' ').title()} Report", styles['Heading1']))
        elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Subheader']))
        elements.append(PageBreak())
        return elements

    def build_footer(self, canvas: Canvas, doc: SimpleDocTemplate):
        """Add footer with page number and configurable content."""
        canvas.saveState()
        footer_config = self.config["pdf_formatting"]["footer"]
        canvas.setFont(footer_config["font"], footer_config["font_size"])
        canvas.setFillColor(HexColor(footer_config["text_color"]))
        footer_text = [footer_config["custom_text"]]
        for field in footer_config["additional_fields"]:
            footer_text.append(self.config["school"].get(field, ""))
        footer_text = " | ".join([t for t in footer_text if t])
        page_number = f"Page {canvas.getPageNumber()}"
        x_position = {
            "left": doc.leftMargin,
            "center": doc.leftMargin + doc.width / 2,
            "right": doc.leftMargin + doc.width
        }[footer_config["alignment"]]
        canvas.drawString(doc.leftMargin, doc.bottomMargin - 20, footer_text)
        canvas.drawRightString(doc.width + doc.leftMargin, doc.bottomMargin - 20, page_number)
        canvas.restoreState()

    def export_to_pdf(self, report_type: str, file_path: str = "", username: Optional[str] = None, role: Optional[str] = None,
                  start_date: Optional[str] = None, end_date: Optional[str] = None,
                  form: Optional[str] = None, stream: Optional[str] = None,
                  department: Optional[str] = None, data: Optional[List] = None,
                  preview: bool = False, parent: Optional[ctk.CTk] = None,
                  buffer: Optional[BytesIO] = None):  
        """Export a report to PDF with professional formatting and optional preview."""
        try:
            # ------------------------------------------------------------------
            # 1. Get the records – either from the manager or from the supplied data
            # ------------------------------------------------------------------
            if data is None:
                if report_type == "overview":
                    records = [self.report_mgr.overview(start_date, end_date)]
                else:
                    records = self.report_mgr.custom_report(
                        [report_type], start_date, end_date, form, stream, department
                    ).get(report_type, [])
            else:
                records = data

            # ------------------------------------------------------------------
            # 2. Normalise every row to a dict (list-of-lists → dict)
            # ------------------------------------------------------------------
            report_configs = {
                "student_summary": ["Admission No", "Name", "Form", "Stream", "Required", "Brought", "Remaining", "Status"],
                "class_summary":   ["Form", "Total Students", "Total Brought", "Total Required", "Remaining", "Percentage"],
                "defaulters":      ["Admission No", "Name", "Form", "Stream", "Required", "Brought", "Remaining"],
                "surplus":         ["Admission No", "Name", "Form", "Stream", "Required", "Brought", "Surplus"],
                "term_summary":    ["Term", "Total Entries", "Total Reams"],
                "issued_summary":  ["Department", "Total Issued"],
                "overview":        ["Total Required", "Total Brought", "Remaining", "Collection %", "Total Issued", "Total Stock"],
                "stream_ream":     ["Admission No", "Name", "Required", "Brought", "Remaining", "Status"]
            }

            if report_type not in report_configs:
                raise ValueError(f"Invalid report type: {report_type}")

            columns = report_configs[report_type]

            # Convert list-of-lists (or mixed) rows to dicts
            normalised = []
            for row in records:
                if isinstance(row, dict):
                    normalised.append(row)
                else:                                   
                    normalised.append(dict(zip(columns, row)))   # list / tuple

            records = normalised

            # ------------------------------------------------------------------
            # 3. Build PDF
            # ------------------------------------------------------------------
            if preview or not file_path:
                temp_file = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
                file_path = temp_file.name
                temp_file.close()

            doc = SimpleDocTemplate(
                file_path,
                pagesize=A4,
                topMargin=self.config["pdf_formatting"]["page_margins"]["top"],
                bottomMargin=self.config["pdf_formatting"]["page_margins"]["bottom"] + 20,
                leftMargin=self.config["pdf_formatting"]["page_margins"]["left"],
                rightMargin=self.config["pdf_formatting"]["page_margins"]["right"]
            )
            elements = []

            # ----------------------styles ---------------------------------------------
            styles = getSampleStyleSheet()
            header_cfg = self.config["pdf_formatting"]["report_headers"].get(report_type,
                                                                            {"text_alignment": "center"})
            align_map = {"left": 0, "center": 1, "right": 2}
            styles.add(ParagraphStyle(name='Header',
                                      fontName=self.config["pdf_formatting"]["header_font"],
                                      fontSize=self.config["pdf_formatting"]["header_font_size"],
                                      textColor=HexColor(self.config["pdf_formatting"]["header_color"]),
                                      spaceAfter=10,
                                      alignment=align_map[header_cfg["text_alignment"]]))
            styles.add(ParagraphStyle(name='Subheader',
                                      fontName=self.config["pdf_formatting"]["subheader_font"],
                                      fontSize=self.config["pdf_formatting"]["subheader_font_size"],
                                      textColor=HexColor(self.config["pdf_formatting"]["header_color"]),
                                      spaceAfter=5,
                                      alignment=align_map[header_cfg["text_alignment"]]))

            # ---- cover page ------------------------------------------------
            elements.extend(self.build_cover_page(report_type, styles))

            # ---- logo / school header --------------------------------------
            logo_path = self.config["school"]["report_logos"].get(report_type,
                                                                 self.config["school"]["logo_path"])
            if os.path.exists(logo_path):
                logo = RLImage(logo_path,
                               width=header_cfg.get("logo_width", 1) * inch,
                               height=header_cfg.get("logo_height", 1) * inch)
                logo.hAlign = header_cfg.get("logo_position", "left").upper()
                elements.append(logo)
            else:
                logger.warning(f"Logo file not found at {logo_path}")
                elements.append(Paragraph("Logo Not Available", styles['Subheader']))

            elements.append(Paragraph(self.config["school"]["name"], styles['Header']))
            elements.append(Paragraph(self.config["school"]["p_o_box"], styles['Subheader']))
            elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                                     styles['Subheader']))
            elements.append(Spacer(1, 0.2 * inch))

            # ---- report title ----------------------------------------------
            elements.append(Paragraph(f"{report_type.replace('_', ' ').title()} Report",
                                     styles['Heading1']))
            elements.append(Spacer(1, 0.2 * inch))

            # ---- filters ---------------------------------------------------
            filters = []
            if start_date:   filters.append(f"Start Date: {start_date}")
            if end_date:     filters.append(f"End Date: {end_date}")
            if form:         filters.append(f"Form: {form}")
            if stream:       filters.append(f"Stream: {stream}")
            if department:   filters.append(f"Department: {department}")
            if filters:
                elements.append(Paragraph("Filters: " + ", ".join(filters), styles['Subheader']))
                elements.append(Spacer(1, 0.1 * inch))

            # ---- table data ------------------------------------------------
            table_data = [columns]                     # header row
            summary_idx = None
            for idx, rec in enumerate(records):
                row = [str(rec.get(col.lower().replace(" ", "_"), "")) for col in columns]

                # Detect the bold summary line that Stream Ream adds
                if any("**" in cell for cell in row):
                    row = [c.replace("**", "").strip() for c in row]
                    summary_idx = idx + 1                 # +1 because of header

                table_data.append(row)

            # ---- table -----------------------------------------------------
            table = Table(table_data)
            style_cmds = [
                ('BACKGROUND', (0, 0), (-1, 0), HexColor(self.config["pdf_formatting"]["table_header_color"])),
                ('TEXTCOLOR',  (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN',      (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME',   (0, 0), (-1, 0), self.config["pdf_formatting"]["table_font"] + '-Bold'),
                ('FONTSIZE',   (0, 0), (-1, 0), self.config["pdf_formatting"]["table_font_size"] + 2),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('FONTNAME',   (0, 1), (-1, -1), self.config["pdf_formatting"]["table_font"]),
                ('FONTSIZE',   (0, 1), (-1, -1), self.config["pdf_formatting"]["table_font_size"]),
                ('BACKGROUND', (0, 1), (-1, -1), HexColor(self.config["pdf_formatting"]["table_row_color"])),
                ('GRID',       (0, 0), (-1, -1), 1, HexColor(self.config["pdf_formatting"]["border_color"])),
                ('BOX',        (0, 0), (-1, -1), 1, HexColor(self.config["pdf_formatting"]["border_color"])),
                ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING',(0, 0), (-1, -1), 8)
            ]

            if summary_idx is not None:
                style_cmds += [
                    ('BACKGROUND', (0, summary_idx), (-1, summary_idx), colors.lightgrey),
                    ('FONTNAME',   (0, summary_idx), (-1, summary_idx), self.config["pdf_formatting"]["table_font"] + '-Bold'),
                    ('FONTSIZE',   (0, summary_idx), (-1, summary_idx), self.config["pdf_formatting"]["table_font_size"] + 1),
                    ('SPAN',       (0, summary_idx), (-1, summary_idx)),
                    ('ALIGN',      (0, summary_idx), (-1, summary_idx), 'CENTER')
                ]

            table.setStyle(TableStyle(style_cmds))
            elements.append(table)

            # ---- build ------------------------------------------------------
            doc.build(elements,
                      onFirstPage=self.build_footer,
                      onLaterPages=self.build_footer)

            # ---- preview / save ---------------------------------------------
            if preview and parent and HAS_PDF2IMAGE:
                PDFPreviewWindow(parent, file_path, report_type)
                return None
            elif preview:
                save_path = ctk.filedialog.asksaveasfilename(defaultextension=".pdf",
                                                             filetypes=[("PDF files", "*.pdf")])
                if save_path:
                    os.rename(file_path, save_path)
                    logger.info(f"Saved PDF to {save_path}")
                    return True
                else:
                    os.remove(file_path)
                    logger.info("PDF not saved, temporary file deleted")
                    return False

            logger.info(f"Exported {report_type} report to PDF at {file_path}")
            return True

        except Exception as e:
            if 'file_path' in locals() and os.path.exists(file_path):
                os.remove(file_path)
            logger.error(f"Error exporting {report_type} to PDF: {e}")
            raise


    def export_to_excel(self, report_type: str, file_path: str, username: Optional[str], role: Optional[str],
                        start_date: Optional[str] = None, end_date: Optional[str] = None,
                        form: Optional[str] = None, stream: Optional[str] = None,
                        department: Optional[str] = None, data: Optional[List] = None):
        """Export a report to Excel with professional formatting."""
        try:
            # --------------------------------------------------------------
            # 1. Get records
            # --------------------------------------------------------------
            if data is None:
                if report_type == "overview":
                    records = [self.report_mgr.overview(start_date, end_date)]
                else:
                    records = self.report_mgr.custom_report(
                        [report_type], start_date, end_date, form, stream, department
                    ).get(report_type, [])
            else:
                records = data

            # --------------------------------------------------------------
            # 2. Normalise to list-of-dicts
            # --------------------------------------------------------------
            report_configs = {
                "student_summary": ["Admission No", "Name", "Form", "Stream", "Required", "Brought", "Remaining", "Status"],
                "class_summary":   ["Form", "Total Students", "Total Brought", "Total Required", "Remaining", "Percentage"],
                "defaulters":      ["Admission No", "Name", "Form", "Stream", "Required", "Brought", "Remaining"],
                "surplus":         ["Admission No", "Name", "Form", "Stream", "Required", "Brought", "Surplus"],
                "term_summary":    ["Term", "Total Entries", "Total Reams"],
                "issued_summary":  ["Department", "Total Issued"],
                "overview":        ["Total Required", "Total Brought", "Remaining", "Collection %", "Total Issued", "Total Stock"],
                "stream_ream":     ["Admission No", "Name", "Required", "Brought", "Remaining", "Status"]
            }

            if report_type not in report_configs:
                raise ValueError(f"Invalid report type: {report_type}")

            columns = report_configs[report_type]

            # Convert list-of-lists to dicts
            normalised = []
            for row in records:
                if isinstance(row, dict):
                    normalised.append(row)
                else:
                    normalised.append(dict(zip(columns, row)))
            records = normalised

            # --------------------------------------------------------------
            # 3. Build DataFrame
            # --------------------------------------------------------------
            rows_for_df = []
            summary_row = None
            for rec in records:
                row = {col: rec.get(col.lower().replace(" ", "_"), "") for col in columns}
                if any("**" in str(v) for v in row.values()):
                    row = {k: str(v).replace("**", "").strip() for k, v in row.items()}
                    summary_row = row
                rows_for_df.append(row)

            df = pd.DataFrame(rows_for_df, columns=columns)

            # --------------------------------------------------------------
            # 4. Write Excel
            # --------------------------------------------------------------
            wb = Workbook()
            ws = wb.active
            ws.title = report_type.replace('_', ' ').title()

            # school header
            ws.append([self.config["school"]["name"]])
            ws.append([self.config["school"]["p_o_box"]])
            ws.append([self.config["school"]["contact"]])
            ws.append([self.config["school"]["motto"]])
            ws.append([self.config["school"]["website"]])
            ws.append([f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"])

            # filters
            filt = []
            if start_date:   filt.append(f"Start Date: {start_date}")
            if end_date:     filt.append(f"End Date: {end_date}")
            if form:         filt.append(f"Form: {form}")
            if stream:       filt.append(f"Stream: {stream}")
            if department:   filt.append(f"Department: {department}")
            if filt:
                ws.append(["Filters: " + ", ".join(filt)])
            ws.append([])                     # spacer

            # column headers
            ws.append(columns)

            # data rows
            for r in df.values:
                ws.append(r.tolist())

            # --------------------------------------------------------------
            # 5. Styling
            # --------------------------------------------------------------
            header_font = Font(name=self.config["excel_formatting"]["header_font"],
                               size=self.config["excel_formatting"]["header_font_size"],
                               bold=self.config["excel_formatting"]["header_bold"],
                               color=self.config["excel_formatting"]["header_text_color"].lstrip('#'))
            cell_font   = Font(name=self.config["excel_formatting"]["cell_font"],
                               size=self.config["excel_formatting"]["cell_font_size"])
            header_fill = PatternFill(start_color=self.config["excel_formatting"]["header_background_color"].lstrip('#'),
                                     end_color=self.config["excel_formatting"]["header_background_color"].lstrip('#'),
                                     fill_type="solid")
            border = Border(left=Side(style='thin',
                                     color=self.config["excel_formatting"]["border_color"].lstrip('#')),
                            right=Side(style='thin',
                                      color=self.config["excel_formatting"]["border_color"].lstrip('#')),
                            top=Side(style='thin',
                                     color=self.config["excel_formatting"]["border_color"].lstrip('#')),
                            bottom=Side(style='thin',
                                        color=self.config["excel_formatting"]["border_color"].lstrip('#')))
            align = Alignment(horizontal='center', vertical='center')

            header_row_idx = 7 if filt else 6
            for cell in ws[header_row_idx]:
                cell.font = header_font
                cell.fill = header_fill
                cell.border = border
                cell.alignment = align

            for row in ws.iter_rows(min_row=header_row_idx + 1,
                                    max_row=ws.max_row,
                                    min_col=1,
                                    max_col=len(columns)):
                for cell in row:
                    cell.font = cell_font
                    cell.border = border
                    cell.alignment = align

            # highlight summary line
            if summary_row:
                sum_row = header_row_idx + len(df)
                for col_idx in range(1, len(columns) + 1):
                    cell = ws.cell(row=sum_row, column=col_idx)
                    cell.font = Font(bold=True, size=11)
                    cell.fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")
                    cell.alignment = Alignment(horizontal='center')
                ws.merge_cells(start_row=sum_row, start_column=1,
                               end_row=sum_row, end_column=len(columns))

            # auto-size columns
            for col in ws.columns:
                max_len = 0
                col_letter = col[0].column_letter
                for cell in col:
                    try:
                        if len(str(cell.value)) > max_len:
                            max_len = len(str(cell.value))
                    except:
                        pass
                ws.column_dimensions[col_letter].width = (max_len + 2) * 1.2

            wb.save(file_path)
            logger.info(f"Exported {report_type} report to Excel at {file_path}")
            return True

        except Exception as e:
            logger.error(f"Error exporting {report_type} to Excel: {e}")
            raise

class PDFPreviewWindow(ctk.CTkToplevel):
    """Custom PDF preview window."""
    def __init__(self, parent, pdf_path: str, report_type: str):
        super().__init__(parent)
        self.title(f"PDF Preview - {report_type.replace('_', ' ').title()} Report")
        self.geometry("800x600")
        self.pdf_path = pdf_path
        self.report_type = report_type
        self.current_page = 0

        # Convert PDF to images
        if not HAS_PDF2IMAGE:
            messagebox.showwarning("Warning",
                "PDF preview is not available. pdf2image (poppler) is required for preview.\n"
                "The PDF has been saved to: " + pdf_path, parent=self)
            self.destroy()
            return
        try:
            self.pages = convert_from_path(pdf_path, dpi=150)
            self.total_pages = len(self.pages)
        except Exception as e:
            logger.error(f"Error converting PDF to images: {e}")
            messagebox.showerror("Error", f"Failed to load PDF: {e}", parent=self)
            self.destroy()
            return

        # GUI elements
        self.canvas = ctk.CTkCanvas(self, bg="#2B2B2B")
        self.canvas.pack(fill="both", expand=True)

        # Navigation frame
        nav_frame = ctk.CTkFrame(self, fg_color="#2B2B2B")
        nav_frame.pack(fill="x", pady=10)
        ctk.CTkButton(
            nav_frame, text="Previous", command=self.prev_page,
            fg_color="#2B6CB0", hover_color="#1E4E79", text_color="#FFFFFF"
        ).pack(side="left", padx=5)
        self.page_label = ctk.CTkLabel(nav_frame, text=f"Page {self.current_page + 1} of {self.total_pages}")
        self.page_label.pack(side="left", padx=10)
        ctk.CTkButton(
            nav_frame, text="Next", command=self.next_page,
            fg_color="#2B6CB0", hover_color="#1E4E79", text_color="#FFFFFF"
        ).pack(side="left", padx=5)
        ctk.CTkButton(
            nav_frame, text="Save", command=self.save_pdf,
            fg_color="#2B6CB0", hover_color="#1E4E79", text_color="#FFFFFF"
        ).pack(side="right", padx=5)
        ctk.CTkButton(
            nav_frame, text="Cancel", command=self.cancel,
            fg_color="#2B6CB0", hover_color="#1E4E79", text_color="#FFFFFF"
        ).pack(side="right", padx=5)

        # Display first page
        self.display_page()

    def display_page(self):
        """Display the current PDF page."""
        if not self.pages:
            return
        # Resize image to fit canvas
        canvas_width = self.canvas.winfo_width() or 800
        canvas_height = self.canvas.winfo_height() or 600
        img = self.pages[self.current_page]
        img_width, img_height = img.size
        scale = min(canvas_width / img_width, canvas_height / img_height) * 0.9
        new_width, new_height = int(img_width * scale), int(img_height * scale)
        img = img.resize((new_width, new_height), PILImage.LANCZOS)
        self.photo = ImageTk.PhotoImage(img)
        self.canvas.delete("all")
        self.canvas.create_image(canvas_width / 2, canvas_height / 2, image=self.photo, anchor="center")
        self.page_label.configure(text=f"Page {self.current_page + 1} of {self.total_pages}")

    def prev_page(self):
        """Show the previous page."""
        if self.current_page > 0:
            self.current_page -= 1
            self.display_page()

    def next_page(self):
        """Show the next page."""
        if self.current_page < self.total_pages - 1:
            self.current_page += 1
            self.display_page()

    def save_pdf(self):
        """Save the PDF to a user-selected location."""
        save_path = ctk.filedialog.asksaveasfilename(defaultextension=".pdf", filetypes=[("PDF files", "*.pdf")])
        if save_path:
            os.rename(self.pdf_path, save_path)
            logger.info(f"Saved PDF to {save_path}")
            messagebox.showinfo("Success", f"PDF saved to {save_path}", parent=self)
            self.destroy()
        else:
            logger.info("PDF save cancelled")
            self.cancel()

    def cancel(self):
        """Close the preview and delete the temporary file."""
        if os.path.exists(self.pdf_path):
            os.remove(self.pdf_path)
            logger.info("PDF preview cancelled, temporary file deleted")
        self.destroy()